services:
  - type: web
    name: databot-labs-backend
    env: node
    rootDir: Backend
    buildCommand: npm ci || npm install
    startCommand: npm start
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
